apiVersion: apps/v1
kind: Deployment
metadata:
  name: vi-service-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vi-service-app
  template:
    metadata:
      labels:
        app: vi-service-app
    spec:
      containers:
      - name: vi-service-app
        image: sumonik/vi-service-app:latest
        ports:
        - containerPort: 3000
        env:
          - name: NODE_ENV
            value: "development"
          - name: TASK_APP_MONGO_URI
            value: "mongodb://mongo:27017/task_db"
---
apiVersion: v1
kind: Service
metadata:
  name: vi-service-app
spec:
  type: ClusterIP 
  selector:
    app: vi-service-app
  ports:
    - protocol: TCP
      port: 80 # Порт, на котором сервис будет доступен внутри кластера
      targetPort: 3000 # Порт контейнера, на который сервис будет направлять трафик
      nodePort: 31000 